spring:
  datasource.url: jdbc:mysql://localhost:3306/human_service
  datasource.username: root
  datasource.password: keep1234
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver

s3:
  bucket: src
  subPath: test
  landing: resources/human-service